### PR TITLE
EOF when remote closes datachannel

### PR DESCRIPTION
**Pull request by ckousik**
#### Description
Earlier, closing a datachannel while a read is active would cause the read to return an `io.EOF` error. A recent patch has caused `Read` to block indefinitely when the remote closes the connection.

#### Reference issue
Fixes #...

### CODE REVIEW

**Comment by ckousik** [comment]
@edaniels might take a while but I'll try to fix this

**Comment by edaniels** [comment]
@ckousik this should be fine now due to the reverts in SCTP. Are you still seeing this with SCTP @ v1.8.5?

**Comment by ckousik** [comment]
yes, sctp is at v1.8.5

**Comment by edaniels** [comment]
Oh interesting. Happen to know which commit is causing the issue?

**Comment by ckousik** [comment]
I'm checking

**Comment by ckousik** [comment]
@edaniels  It breaks on [commit `f31b9348f7e4fdd47d00be05a72ea5a619995ce4`](https://github.com/pion/sctp/commit/f31b9348f7e4fdd47d00be05a72ea5a619995ce4) in `pion/sctp` and also subsequent commits.

**Comment by ckousik** [comment]
The `Read` call on a datachannel returns `io.EOF` when using SCTP@1.8.4, which is the expected behaviour. Now it just blocks indefinitely.

**Comment by edaniels** [comment]
Got it. In this case, it doesn't seem like much of a regression since that code was reverted within 24 hours so it doesn't seem like it would have gotten much usage. I agree that you do probably want to see an EOF however.

**Comment by ckousik** [comment]
@edaniels Going through https://github.com/ckousik/datachannel/blob/master/datachannel.go#L193 and https://github.com/pion/sctp/blob/master/stream.go#L336, the behaviour is as expected. In our case, we have one end of the stream that reading and the remote is only writing (rare case but need to test). So if the reading stream calls close, and the writing stream does not read, the datachannel does not properly close. Btw these are detached datachannels.

**Comment by ckousik** [comment]
@edaniels Sorry to keep reopening this, but I've created a [new issue](https://github.com/pion/datachannel/issues/162) . The expected behaviour after looking at https://github.com/pion/datachannel/blob/master/datachannel.go#L193 leads me to believe that a remote sending a reset chunk on a stream should cause any `Read` to return EOF.

**Comment by edaniels** [comment]
Yeah I believe the issue is legit and requires a fix. I just don't think it's really a regression unless you were expecting some kind of behavior in sctp between c0159aa2d49c240362038edf88baa8a9e6cfcede to 6e962c66d1fe66ec4347f35b000d28f010443778. After that point in time, I reverted c0159aa2d49c240362038edf88baa8a9e6cfcede. Is there a commit I'm missing?

**Comment by ckousik** [comment]
I agree that it's not a regression. I renamed the PR.

**Pull request closed without merging**
